#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt', '>= 2.6.0'
cookbook 'ufw', '>= 0.7.4'
cookbook 'java', '>= 3.1.2'

cookbook 'cassandra',
    :git => 'https://github.com/michaelklishin/cassandra-chef-cookbook',
    :ref => 'v2.8.0'
